services:
  - name: backend-service
    type: web
    env: node
    rootDir: be
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: my-database
          property: connectionString

  - name: frontend-service
    type: static
    rootDir: fe
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    envVars:
      - key: VITE_baseURL
        value: https://backend-service.onrender.com
